ALTER TABLE FoodGroups ADD ArabicName NVARCHAR(150) NULL;
ALTER TABLE FoodItems ADD ArabicName NVARCHAR(250) NULL;
GO
ALTER TABLE AppSettings ADD DefaultOrderType INT NOT NULL DEFAULT 1;
GO

ALTER TABLE AppSettings ADD InvoiceLogo NVARCHAR(MAX) NULL;
GO

ALTER TABLE AppSettings ADD PrinterMethod INT NOT NULL DEFAULT 0;
ALTER TABLE AppSettings ADD PrinterPaperWidth INT NOT NULL DEFAULT 80;
GO
ALTER TABLE AppSettings ADD SkipKitchenOrder BIT NOT NULL DEFAULT 0;
GO
