IF NOT EXISTS (
  SELECT * 
  FROM INFORMATION_SCHEMA.COLUMNS 
  WHERE TABLE_NAME = 'FoodItems' AND COLUMN_NAME = 'Barcode'
)
BEGIN
    ALTER TABLE FoodItems ADD Barcode NVARCHAR(MAX) NULL;
END
GO

IF NOT EXISTS (
  SELECT * 
  FROM INFORMATION_SCHEMA.COLUMNS 
  WHERE TABLE_NAME = 'FoodItems' AND COLUMN_NAME = 'VanSalePrice'
)
BEGIN
    ALTER TABLE FoodItems ADD VanSalePrice DECIMAL(18,2) NOT NULL DEFAULT 0;
END
GO

IF NOT EXISTS (
  SELECT * 
  FROM INFORMATION_SCHEMA.COLUMNS 
  WHERE TABLE_NAME = 'FoodItems' AND COLUMN_NAME = 'WholeSalePrice'
)
BEGIN
    ALTER TABLE FoodItems ADD WholeSalePrice DECIMAL(18,2) NOT NULL DEFAULT 0;
END
GO

IF NOT EXISTS (
  SELECT * 
  FROM INFORMATION_SCHEMA.COLUMNS 
  WHERE TABLE_NAME = 'Expenses' AND COLUMN_NAME = 'Category'
)
BEGIN
    ALTER TABLE Expenses ADD Category NVARCHAR(500) NULL;
END
GO

IF NOT EXISTS (
  SELECT * 
  FROM INFORMATION_SCHEMA.COLUMNS 
  WHERE TABLE_NAME = 'Expenses' AND COLUMN_NAME = 'Item'
)
BEGIN
    ALTER TABLE Expenses ADD Item NVARCHAR(500) NULL;
END
GO
