SELECT 
    '#### Table: ' + TABLE_NAME + CHAR(13) + CHAR(10) +
    STRING_AGG('- ' + COLUMN_NAME + ' (' + DATA_TYPE + ')', CHAR(13) + CHAR(10)) 
    WITHIN GROUP (ORDER BY ORDINAL_POSITION) + CHAR(13) + CHAR(10)
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'dbo'
GROUP BY TABLE_NAME
ORDER BY TABLE_NAME;
